fixed bug: enable acc nav mode
JSKAerialRobot/aerial_robot pull request #449
Opened 2021-02-13 09:57 UTC by kanke-hayata

I fixeda a bug that hydrus switches to pos_nav mode soon after it changed to acc_nav mode.

2021-02-13 21:25 UTC, tongtybj commented
@kanke-hayata 

can you unify  the indent of the new line?

2021-02-13 21:37 UTC, tongtybj reviewed
can you unify the indent of the new line?

2021-02-14 08:48 UTC, chibi314 requested changes
インデント直したらOK

2021-02-17 13:48 UTC, kanke-hayata commented
I modified the Indent.

2021-02-17 17:06 UTC, chibi314 approved these changes

2021-02-17 20:05 UTC, tongtybj approved these changes

2021-02-17 20:06 UTC, merged